{% set version = "2020.12.04" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-isocodes
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ISOcodes_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ISOcodes/ISOcodes_{{ version }}.tar.gz
  sha256: 5dced6b66ce403f01c80bb59e0b61aa2258e67cf70b99d9bf0a7f20a671e67a0

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('ISOcodes')"           # [not win]
    - "\"%R%\" -e \"library('ISOcodes')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ISOcodes
  license: GPL-2
  summary: ISO language, territory, currency, script and character codes. Provides ISO 639 language codes, ISO 3166 territory codes, ISO 4217 currency codes, ISO 15924 script codes, and the ISO 8859 character codes as well as the UN M.49 area codes.
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - stevierene82
    - conda-forge/r

# Package: ISOcodes
# Version: 2019.04.22
# Encoding: UTF-8
# Title: Selected ISO Codes
# Authors@R: c(person("Christian", "Buchta", role = "aut"), person("Kurt", "Hornik", role = c("aut", "cre"), email = "Kurt.Hornik@R-project.org", comment = c(ORCID = "0000-0003-4198-9911")))
# Description: ISO language, territory, currency, script and character codes. Provides ISO 639 language codes, ISO 3166 territory codes, ISO 4217 currency codes, ISO 15924 script codes, and the ISO 8859 character codes as well as the UN M.49 area codes.
# Depends: R (>= 2.10.0)
# License: GPL-2
# LazyData: yes
# NeedsCompilation: no
# Packaged: 2019-04-23 07:24:35 UTC; hornik
# Author: Christian Buchta [aut], Kurt Hornik [aut, cre] (<https://orcid.org/0000-0003-4198-9911>)
# Maintainer: Kurt Hornik <Kurt.Hornik@R-project.org>
# Repository: CRAN
# Date/Publication: 2019-04-23 07:34:40 UTC
