appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: cmG/PuBeDgY2e/bMKRQl41X1U/RN7pwXNZaJQYAOTYubEJ4iCZkihpaTU/mNnHD/4M6J+Sp13cvCFu9xISMg6z65o0McImQRtHZDO40KR2OtLKy1cN87B3mRM81BdEIQ4aMmlD5mauoQxhPQ6vXqHYImYypUg9wjEz/fO8jLwzWCnBbc17TCt0C87IVnbhwiE6BRku1X0oP6NA9KlNTi2E6jCoMmqBLEtbepzyhag4kgYTO8KnccGxtNOfA09Gin2xyz3ovkZmHBZNdKQzb+U447cParrOO7nX16uTDRhMJg/1rZ1dmW41aIzldKFma18YlY0JzkWAcBPttwIGnoIe9LD9a7pOcZMSgnLRL54IJGRCjrVNRpKCY4jbUzrFzDui+RdflIO8ufX33k6k96SMVi7AY33NyTawp1QN4GbTeT7cGTNu0/JmTBOi7dIJ6Iwf2QVP/Emq7BLXso+9wJ700VUHubIsh/vDVe50vhin84hnOFXBQ2LeZpJeiPW/jtqeUVb63fYwHc2E8zwlfZnaLuuAtZX5TqOF1CfLLyTPJgClBbQo0EyzOPEwaq1K78BA0dWvQfetEHSrao3tySAweWRtMLhjL++YT8nmy01o0yDIbVxYisccwMn7n65VQnIOdddudM/gSRdZqJKBJ2AaBWH9FXZkdwiDPQLjwDkFY=
conda_forge_output_validation: true
